In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings
from scipy.stats import f_oneway
warnings.filterwarnings('ignore')

In [2]:
dengue = pd.read_csv('dengue.csv')
dengue

Month  Year    Region  Dengue_Cases  Dengue_Deaths
0       January  2016  Region I           705              1
1      February  2016  Region I           374              0
2         March  2016  Region I           276              0
3         April  2016  Region I           240              2
4           May  2016  Region I           243              1
...         ...   ...       ...           ...            ...
1015     August  2020     BARMM            91              0
1016  September  2020     BARMM            16              8
1017    October  2020     BARMM            13              9
1018   November  2020     BARMM            15              1
1019   December  2020     BARMM            23              0

[1020 rows x 5 columns]

In [3]:
dengue.dtypes

Month            object
Year              int64
Region           object
Dengue_Cases      int64
Dengue_Deaths     int64
dtype: object

In [9]:
dengue['Year'] = dengue['Year'].astype('int')
dengue['Month'] = dengue['Month'].astype('str')

In [10]:
dengue.dtypes

Month            object
Year              int64
Region           object
Dengue_Cases      int64
Dengue_Deaths     int64
dtype: object

In [11]:
# Combine Month and Year into a Date column
dengue['Date'] = pd.to_datetime(dengue['Month'] + ' ' + dengue['Year'].astype(str))

# Optional: sort by date
dengue = dengue.sort_values('Date')

In [13]:
region_df = dengue[dengue['Region'] == 'Region IV-A']
monthly_death = region_df.groupby('Date')['Dengue_Deaths'].sum().reset_index()

In [15]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Convert dates to ordinal for regression

monthly_death['Date_Ordinal'] = monthly_cases['Date'].map(pd.Timestamp.toordinal)

# # # Reshape for sklearn
X = monthly_death['Date_Ordinal'].values.reshape(-1, 1) #independent variable 
y = monthly_death['Dengue_Deaths'].values   #dependent variable 

# # # Fit model
model = LinearRegression()
model.fit(X, y)

# # # Predict
monthly_death['Predicted_Cases'] = model.predict(X)

# # # Evaluate: R-squared
r_squared = model.score(X, y)
print(f"The model explains {r_squared:.1%} of the variation in dengue death.")


The model explains 0.2% of the variation in dengue death.


In [16]:
monthly_death

Date  Dengue_Deaths  Date_Ordinal  Predicted_Cases
0  2016-01-01             14        735964        10.035293
1  2016-02-01              5        735995        10.064005
2  2016-03-01              9        736024        10.090864
3  2016-04-01              1        736055        10.119576
4  2016-05-01              1        736085        10.147362
5  2016-06-01              4        736116        10.176073
6  2016-07-01              6        736146        10.203859
7  2016-08-01              2        736177        10.232571
8  2016-09-01             28        736208        10.261282
9  2016-10-01             20        736238        10.289068
10 2016-11-01             10        736269        10.317779
11 2016-12-01              8        736299        10.345565
12 2017-01-01             14        736330        10.374277
13 2017-02-01              5        736361        10.402988
14 2017-03-01              2        736389        10.428921
15 2017-04-01              0        736420        10.457633
16 2017-05-01              1        736450        10.485419
17 2017-06-01              5        736481        10.514130
18 2017-07-01              5        736511        10.541916
19 2017-08-01             17        736542        10.570628
20 2017-09-01              6        736573        10.599339
21 2017-10-01             20        736603        10.627125
22 2017-11-01             21        736634        10.655836
23 2017-12-01             14        736664        10.683622
24 2018-01-01             17        736695        10.712334
25 2018-02-01              9        736726        10.741045
26 2018-03-01             10        736754        10.766978
27 2018-04-01             10        736785        10.795690
28 2018-05-01              4        736815        10.823476
29 2018-06-01              2        736846        10.852187
30 2018-07-01             17        736876        10.879973
31 2018-08-01             18        736907        10.908685
32 2018-09-01             31        736938        10.937396
33 2018-10-01             18        736968        10.965182
34 2018-11-01             16        736999        10.993893
35 2018-12-01              5        737029        11.021679
36 2019-01-01              6        737060        11.050391
37 2019-02-01             14        737091        11.079102
38 2019-03-01             13        737119        11.105035
39 2019-04-01              3        737150        11.133747
40 2019-05-01              9        737180        11.161533
41 2019-06-01              8        737211        11.190244
42 2019-07-01             21        737241        11.218030
43 2019-08-01             39        737272        11.246742
44 2019-09-01             48        737303        11.275453
45 2019-10-01             37        737333        11.303239
46 2019-11-01             23        737364        11.331950
47 2019-12-01             21        737394        11.359736
48 2020-01-01             11        737425        11.388448
49 2020-02-01              3        737456        11.417159
50 2020-03-01              6        737485        11.444019
51 2020-04-01              0        737516        11.472730
52 2020-05-01              1        737546        11.500516
53 2020-06-01              0        737577        11.529228
54 2020-07-01              0        737607        11.557013
55 2020-08-01              1        737638        11.585725
56 2020-09-01              4        737669        11.614436
57 2020-10-01              2        737699        11.642222
58 2020-11-01              3        737730        11.670934
59 2020-12-01              4        737760        11.698719

In [17]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
dengue['Outbreak'] = (dengue['Dengue_Cases'] > 5000).astype(int)

In [21]:
dengue

Month  Year       Region  Dengue_Cases  Dengue_Deaths       Date  \
0      January  2016     Region I           705              1 2016-01-01   
840    January  2016          NCR          1261              4 2016-01-01   
780    January  2016  Region XIII          1116              6 2016-01-01   
240    January  2016  Region IV-B           203              1 2016-01-01   
120    January  2016   Region III          1976              3 2016-01-01   
...        ...   ...          ...           ...            ...        ...   
119   December  2020    Region II            96              0 2020-12-01   
899   December  2020          NCR           658              4 2020-12-01   
59    December  2020     Region I          1081              1 2020-12-01   
659   December  2020     Region X           281              1 2020-12-01   
1019  December  2020        BARMM            23              0 2020-12-01   

      Outbreak  
0            0  
840          0  
780          0  
240          0  
120          0  
...        ...  
119          0  
899          0  
59           0  
659          0  
1019         0  

[1020 rows x 7 columns]

In [22]:
# Encode categorical features
df_encoded = pd.get_dummies(dengue[['Region', 'Month']], drop_first=True)

# Combine with numerical features
df_model = pd.concat([df_encoded, dengue[['Year', 'Dengue_Cases', 'Outbreak']]], axis=1)

In [23]:
df_encoded

Region_CAR  Region_NCR  Region_Region I  Region_Region II  \
0          False       False             True             False   
840        False        True            False             False   
780        False       False            False             False   
240        False       False            False             False   
120        False       False            False             False   
...          ...         ...              ...               ...   
119        False       False            False              True   
899        False        True            False             False   
59         False       False             True             False   
659        False       False            False             False   
1019       False       False            False             False   

      Region_Region III  Region_Region IV-A  Region_Region IV-B  \
0                 False               False               False   
840               False               False               False   
780               False               False               False   
240               False               False                True   
120                True               False               False   
...                 ...                 ...                 ...   
119               False               False               False   
899               False               False               False   
59                False               False               False   
659               False               False               False   
1019              False               False               False   

      Region_Region IX  Region_Region V  Region_Region VI  ...  \
0                False            False             False  ...   
840              False            False             False  ...   
780              False            False             False  ...   
240              False            False             False  ...   
120              False            False             False  ...   
...                ...              ...               ...  ...   
119              False            False             False  ...   
899              False            False             False  ...   
59               False            False             False  ...   
659              False            False             False  ...   
1019             False            False             False  ...   

      Month_December  Month_February  Month_January  Month_July  Month_June  \
0              False           False           True       False       False   
840            False           False           True       False       False   
780            False           False           True       False       False   
240            False           False           True       False       False   
120            False           False           True       False       False   
...              ...             ...            ...         ...         ...   
119             True           False          False       False       False   
899             True           False          False       False       False   
59              True           False          False       False       False   
659             True           False          False       False       False   
1019            True           False          False       False       False   

      Month_March  Month_May  Month_November  Month_October  Month_September  
0           False      False           False          False            False  
840         False      False           False          False            False  
780         False      False           False          False            False  
240         False      False           False          False            False  
120         False      False           False          False            False  
...           ...        ...             ...            ...              ...  
119         False      False           False          False            False  
899         False     

In [24]:
from sklearn.model_selection import train_test_split

X = df_model.drop('Outbreak', axis=1)
y = df_model['Outbreak']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)


LogisticRegression(max_iter=5000)

In [27]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[197   0]
 [  0   7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       197
           1       1.00      1.00      1.00         7

    accuracy                           1.00       204
   macro avg       1.00      1.00      1.00       204
weighted avg       1.00      1.00      1.00       204



In [36]:
def classify_severity(cases):
    if cases < 500:
        return 0
    elif cases <= 5000:
        return 1
    else:
        return 2

dengue['Severity'] = dengue['Dengue_Cases'].apply(classify_severity)

In [37]:
dengue.dtypes

Month                    object
Year                      int64
Region                   object
Dengue_Cases              int64
Dengue_Deaths             int64
Date             datetime64[ns]
Outbreak                  int64
Severity                  int64
dtype: object

In [38]:
# Encode categorical features
df_encoded = pd.get_dummies(dengue[['Region', 'Month']], drop_first=True)

# Combine with numerical features
df_model = pd.concat([df_encoded, dengue[['Year', 'Dengue_Cases', 'Severity']]], axis=1)
df_model

Region_CAR  Region_NCR  Region_Region I  Region_Region II  \
0          False       False             True             False   
840        False        True            False             False   
780        False       False            False             False   
240        False       False            False             False   
120        False       False            False             False   
...          ...         ...              ...               ...   
119        False       False            False              True   
899        False        True            False             False   
59         False       False             True             False   
659        False       False            False             False   
1019       False       False            False             False   

      Region_Region III  Region_Region IV-A  Region_Region IV-B  \
0                 False               False               False   
840               False               False               False   
780               False               False               False   
240               False               False                True   
120                True               False               False   
...                 ...                 ...                 ...   
119               False               False               False   
899               False               False               False   
59                False               False               False   
659               False               False               False   
1019              False               False               False   

      Region_Region IX  Region_Region V  Region_Region VI  ...  Month_July  \
0                False            False             False  ...       False   
840              False            False             False  ...       False   
780              False            False             False  ...       False   
240              False            False             False  ...       False   
120              False            False             False  ...       False   
...                ...              ...               ...  ...         ...   
119              False            False             False  ...       False   
899              False            False             False  ...       False   
59               False            False             False  ...       False   
659              False            False             False  ...       False   
1019             False            False             False  ...       False   

      Month_June  Month_March  Month_May  Month_November  Month_October  \
0          False        False      False           False          False   
840        False        False      False           False          False   
780        False        False      False           False          False   
240        False        False      False           False          False   
120        False        False      False           False          False   
...          ...          ...        ...             ...            ...   
119        False        False      False           False          False   
899        False        False      False           False          False   
59         False        False      False           False          False   
659        False        False      False           False          False   
1019       False        False      False           False          False   

      Month_September  Year  Dengue_Cases  Severity  
0               False  2016           705         1  
840             False  2016          1261         1  
780             False  2016          1116         1  
240             False  2016           203         0  
120             False  2016          1976         1  
...               ...   ...           ...       ...  
119             False  2020            96         0  
899             False  2020           658         1  
59              False  2020          1081         1  
659             Fa

In [39]:
from sklearn.model_selection import train_test_split

X = df_model.drop('Severity', axis=1)
y = df_model['Severity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
from sklearn.linear_model import LogisticRegression

# Multinomial logistic regression
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=5000)
model.fit(X_train, y_train)


LogisticRegression(max_iter=5000, multi_class='multinomial')

In [42]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[97  1  0]
 [ 0 99  0]
 [ 0  0  7]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99        98
           1       0.99      1.00      0.99        99
           2       1.00      1.00      1.00         7

    accuracy                           1.00       204
   macro avg       1.00      1.00      1.00       204
weighted avg       1.00      1.00      1.00       204

